project:
  type: website
  output-dir: _site

website:
  title: "CB_DOC"
  site-url: "https://edy888.github.io/doc/"

  navbar:
    left:
      - text: "Home"
        href: index.qmd

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "AS SCI"
        contents:
          - text: "ATP Checkout (Atellica + SH) â€” Startup Instructions"
            href: "1. AS SCI/1. Installation/1. Atellica Sample Handler Configurations/1. Startup Instructions - Service Startup/AS_SH_ATP.qmd"

format:
  html:
    toc: true
    toc-depth: 6

execute:
  enabled: false

freeze: auto