project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - "1. AS SCI/1. Installation/1. Atellica Sample Handler Configurations/1. Startup Instructions - Service Startup/AS_SH_ATP.qmd"

website:
  title: "CB_DOC"

format:
  html:
    toc: true

execute:
  enabled: false
  freeze: auto

